CREATE TABLE HTML (  メソッド VARCHAR(100), 出来ること VARCHAR(500), リンク VARCHAR(500)  );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<!DOCTYPE html>','ドキュメントタイプを宣言する','http://www.htmq.com/html5/doctype.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<html>','HTML文書であることを示す','http://www.htmq.com/html5/html.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<head>','文書のヘッダ情報を表す','http://www.htmq.com/html5/head.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<title>','文書にタイトルをつける','http://www.htmq.com/html5/title.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<base>','相対パスの基準URIを指定する','http://www.htmq.com/html5/base.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<link>','リンクする外部リソースを指定する','http://www.htmq.com/html5/link.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<meta>','その文書に関する情報（メタデータ）を指定する','http://www.htmq.com/html5/meta.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<style>','スタイルシートを記述する','http://www.htmq.com/html5/style.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<script>','文書にJavaScriptなどのスクリプトを組み込む','http://www.htmq.com/html5/script.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<noscript>','スクリプトが動作しない環境用の表示内容を指定する','http://www.htmq.com/html5/noscript.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<body>','文書の本体を表す','http://www.htmq.com/html5/body.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<section>','一つのセクションであることを示す','http://www.htmq.com/html5/section.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<nav>','ナビゲーションであることを示す','http://www.htmq.com/html5/nav.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<article>','記事であることを示す','http://www.htmq.com/html5/article.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<aside>','余談・補足情報のセクションであることを示す','http://www.htmq.com/html5/aside.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<h1>-<h6>','見出しを付ける','http://www.htmq.com/html5/h.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<hgroup>','セクションの見出しを表す、見出しをまとめる【廃止予定】','http://www.htmq.com/html5/hgroup.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<header>','ヘッダであることを示す','http://www.htmq.com/html5/header.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<footer>','フッタであることを示す','http://www.htmq.com/html5/footer.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<address>','連絡先・問合せ先を表す','http://www.htmq.com/html5/address.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<p>','ひとつの段落（パラグラフ）であることを表す','http://www.htmq.com/html5/p.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<hr>','テーマや話題の区切りを表す','http://www.htmq.com/html5/hr.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<pre>','半角スペースや改行をそのまま表示する','http://www.htmq.com/html5/pre.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<blockquote>','引用・転載セクションであることを表す','http://www.htmq.com/html5/blockquote.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<ol>','順序のあるリストを表示する','http://www.htmq.com/html5/ol.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<ul>','順序のないリストを表示する','http://www.htmq.com/html5/ul.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<li>','リストの項目を記述する','http://www.htmq.com/html5/li.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<dl>','定義・説明リストを表す','http://www.htmq.com/html5/dl.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<dt>','定義・説明される言葉を表す','http://www.htmq.com/html5/dt.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<dd>','定義用語や言葉の説明をする','http://www.htmq.com/html5/dd.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<figure>','図表であることを示す','http://www.htmq.com/html5/figure.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<figcaption>','図表のキャプションを示す','http://www.htmq.com/html5/figcaption.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<div>','ひとかたまりの範囲として定義する','http://www.htmq.com/html5/div.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<main>','メインコンテンツであることを示す','null' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<a>','ハイパーリンクを指定する','http://www.htmq.com/html5/a.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<em>','強勢する（アクセントを付ける）箇所を表す','http://www.htmq.com/html5/em.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<strong>','強い重要性を表す','http://www.htmq.com/html5/strong.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<small>','免責・警告・著作権などの注釈や細目を表す','http://www.htmq.com/html5/small.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<s>','すでに正確ではなくなった内容を表す','http://www.htmq.com/html5/s.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<cite>','作品のタイトルを表す','http://www.htmq.com/html5/cite.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<q>','引用句・引用文であることを表す','http://www.htmq.com/html5/q.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<dfn>','用語が使用されていることを示す','http://www.htmq.com/html5/dfn.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<abbr>','略語や頭字語であることを表す','http://www.htmq.com/html5/abbr.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<time>','日付や時刻を正確に示す','http://www.htmq.com/html5/time.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<code>','プログラムなどのコードであることを示す','http://www.htmq.com/html5/code.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<var>','変数であることを示す','http://www.htmq.com/html5/var.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<samp>','プログラムによる出力結果のサンプルであることを示す','http://www.htmq.com/html5/samp.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<kbd>','ユーザーが入力する内容であることを示す','http://www.htmq.com/html5/kbd.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<sub>','下付き文字を表す','http://www.htmq.com/html5/sub.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<sup>','上付き文字を表す','http://www.htmq.com/html5/sup.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<i>','声や心の中で思ったことなど、他と区別したいテキストを表す','http://www.htmq.com/html5/i.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<b>','文書内のキーワードや製品名など、他と区別したいテキストを表す','http://www.htmq.com/html5/b.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<mark>','文書内の該当テキストを目立たせる','http://www.htmq.com/html5/mark.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<ruby>','ルビをふる','http://www.htmq.com/html5/ruby.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<rt>','ルビのテキストを指定する','http://www.htmq.com/html5/rt.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<rp>','ルビを囲む記号を指定する','http://www.htmq.com/html5/rp.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<bdo>','文字表記の方向を指定する','http://www.htmq.com/html5/bdo.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<span>','ひとつの範囲として定義する','http://www.htmq.com/html5/span.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<br>','改行する','http://www.htmq.com/html5/br.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<wbr>','改行しても良い位置を示す','http://www.htmq.com/html5/wbr.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<ins>','追加された部分であることを示す','http://www.htmq.com/html5/ins.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<del>','削除された部分であることを示す','http://www.htmq.com/html5/del.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<img>','画像を表示する','http://www.htmq.com/html5/img.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<iframe>','インラインフレームを作る','http://www.htmq.com/html5/iframe.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<embed>','プラグインデータを埋め込む','http://www.htmq.com/html5/embed.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<object>','文書に外部リソースを埋め込む','http://www.htmq.com/html5/object.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<param>','プラグインのパラメータを指定する','http://www.htmq.com/html5/param.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<video>','動画を再生する','http://www.htmq.com/html5/video.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<audio>','音声を再生する','http://www.htmq.com/html5/audio.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<source>','動画や音声などのURLや種類を指定する','http://www.htmq.com/html5/source.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<canvas>','図形を描く','http://www.htmq.com/html5/canvas.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<map>','イメージマップを作成する','http://www.htmq.com/html5/map.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<area>','イメージマップのハイパーリンク領域を設定する','http://www.htmq.com/html5/area.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<table>','テーブル（表）を作成する','http://www.htmq.com/html5/table.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<caption>','テーブル（表）にキャプションをつける','http://www.htmq.com/html5/caption.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<colgroup>','表の縦列をグループ化する','http://www.htmq.com/html5/colgroup.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<col>','表の縦列の属性やスタイルを指定する','http://www.htmq.com/html5/col.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<tbody>','テーブル（表）のボディ部分を定義する','http://www.htmq.com/html5/tbody.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<thead>','テーブル（表）のヘッダ部分を定義する','http://www.htmq.com/html5/thead.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<tfoot>','テーブル（表）のフッタ部分を定義する','http://www.htmq.com/html5/tfoot.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<tr>','テーブル（表）の横一行を定義する','http://www.htmq.com/html5/tr.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<td>','テーブル（表）のデータセルを作成する','http://www.htmq.com/html5/td.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<th>','テーブル（表）の見出しセルを作成する','http://www.htmq.com/html5/th.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<form>','入力・送信フォームを作る','http://www.htmq.com/html5/form.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<fieldset>','フォームの入力項目をグループ化する','http://www.htmq.com/html5/fieldset.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<legend>','フォームの入力項目グループにキャプションを付ける','http://www.htmq.com/html5/legend.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<label>','フォーム部品と項目名（ラベル）を関連付ける','http://www.htmq.com/html5/label.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input>','フォームを構成する様々な入力部品を作成する','http://www.htmq.com/html5/input.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="hidden">','画面上は表示されない隠しデータを指定する','http://www.htmq.com/html5/input_type_hidden.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="text">','一行テキストボックスを作成する','http://www.htmq.com/html5/input_type_text.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="search">','検索テキストの入力欄を作成する','http://www.htmq.com/html5/input_type_search.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="tel">','電話番号の入力欄を作成する','http://www.htmq.com/html5/input_type_tel.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="url">','URLの入力欄を作成する','http://www.htmq.com/html5/input_type_url.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="email">','メールアドレスの入力欄を作成する','http://www.htmq.com/html5/input_type_email.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="password">','パスワード入力欄を作成する','http://www.htmq.com/html5/input_type_password.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="datetime">','協定世界時による日時の入力欄を作成する','http://www.htmq.com/html5/input_type_datetime.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="date">','日付の入力欄を作成する','http://www.htmq.com/html5/input_type_date.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="month">','月の入力欄を作成する','http://www.htmq.com/html5/input_type_month.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="week">','週の入力欄を作成する','http://www.htmq.com/html5/input_type_week.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="time">','時間の入力欄を作成する','http://www.htmq.com/html5/input_type_time.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="datetime-local">','ローカル日時の入力欄を作成する','http://www.htmq.com/html5/input_type_datetime-local.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="number">','数値の入力欄を作成する','http://www.htmq.com/html5/input_type_number.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="range">','レンジ入力欄を作成する','http://www.htmq.com/html5/input_type_range.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="color">','色の入力欄を作成する','http://www.htmq.com/html5/input_type_color.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="checkbox">','チェックボックスを作成する','http://www.htmq.com/html5/input_type_checkbox.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="radio">','ラジオボタンを作成する','http://www.htmq.com/html5/input_type_radio.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="file">','サーバーへファイルを送信する','http://www.htmq.com/html5/input_type_file.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="submit">','送信ボタンを作成する','http://www.htmq.com/html5/input_type_submit.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="image">','画像ボタンを作成する','http://www.htmq.com/html5/input_type_image.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="reset">','リセットボタンを作成する','null' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input type="button">','汎用ボタンを作成する','http://www.htmq.com/html5/input_type_button.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input autofocus>','入力欄にカーソルを当てて自動フォーカスする','http://www.htmq.com/html5/input_autofocus.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input placeholder>','入力欄に初期表示する内容を指定する','http://www.htmq.com/html5/input_placeholder.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input required>','入力必須であることを示す','http://www.htmq.com/html5/input_required.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input pattern>','正規表現で入力値のパターンを指定する','http://www.htmq.com/html5/input_pattern.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input min max>','入力できる最小値と最大値を指定する','http://www.htmq.com/html5/input_min.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input step>','入力欄で刻むステップ値を指定する','http://www.htmq.com/html5/input_step.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input autocomplete>','入力候補を提示して入力内容を自動補完する','http://www.htmq.com/html5/input_autocomplete.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<input multiple>','複数の値を入力・選択できるようにする','http://www.htmq.com/html5/input_multiple.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<button>','ボタンを作成する','http://www.htmq.com/html5/button.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<select>','セレクトボックスを作成する','http://www.htmq.com/html5/select.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<datalist>','入力候補となるデータリストを定義する','http://www.htmq.com/html5/datalist.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<optgroup>','選択肢をグループ化する','http://www.htmq.com/html5/optgroup.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<option>','セレクトボックスや入力候補リストの選択肢を指定する','http://www.htmq.com/html5/option.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<textarea>','複数行のテキスト入力欄を作成する','http://www.htmq.com/html5/textarea.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<keygen>','フォーム送信時にキーを発行する','http://www.htmq.com/html5/keygen.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<output>','計算結果を示す','http://www.htmq.com/html5/output.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<progress>','タスク完了までの進行状況を示す','http://www.htmq.com/html5/progress.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<meter>','規定範囲内の測定値を表す','http://www.htmq.com/html5/meter.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<details>','備考や操作手段などの詳細情報を示す','http://www.htmq.com/html5/details.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<summary>','<details>の内容の要約を示す','http://www.htmq.com/html5/summary.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<command>','操作メニューの各コマンドを指定する','http://www.htmq.com/html5/command.shtml' );
INSERT INTO HTML ( メソッド,出来ること,リンク ) VALUES ( '<menu>','操作メニューを作成する','http://www.htmq.com/html5/menu.shtml' );
